# FOR AGGREGATED MODE
# If you want to generate the router args in a different location,
# you can change the build_extensions key to the desired location.
builders:
  args_generator:
    import: "package:args_generator/args_generator.dart"
    builder_factories: ["argsGenerator"]
    build_extensions:
      r'$package$': ["lib/generated/args/router.args.g.dart"]
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        mode: "aggregated"
