builders:
  args_generator:
    import: "package:args_generator/args_generator.dart"
    builder_factories: ["pageArgsGenerator"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]